<?php
/**
 * @file
 * Hooks implementations for the GraphicsMagick module.
 */

use \graphicsmagick\Utility\Color;

 /**
 * Implements hook_autoload_info().
 */
function graphicsmagick_autoload_info() {
  return array(
    'graphicsmagick\Utility\Color' => 'includes/color.class.inc',
  );
}

/**
 * Implements hook_image_effect_info().
 */
function graphicsmagick_image_effect_info() {
  $effects = array();

  $effects['graphicsmagick_effects_blur'] = array(
    'label' => t('Blur'),
    'help' => t('This effect will make the image details less distinct. A Gaussian operator with the given radius and standard deviation (sigma) will be applied.'),
    'dimensions passthrough' => TRUE,
    'form callback' => 'graphicsmagick_effects_blur_form',
    'effect callback' => 'graphicsmagick_effects_blur',
    'summary theme' => 'graphicsmagick_effects_blur_summary',
  );

  $effects['graphicsmagick_effects_despeckle'] = array(
    'label' => t('Despeckle'),
    'help' => t('This effect will reduce the speckle noise in an image while preserving the original image edges.'),
    'dimensions passthrough' => TRUE,
    'effect callback' => 'graphicsmagick_effects_despeckle',
  );

  $effects['graphicsmagick_effects_edge'] = array(
    'label' => t('Edge enhance'),
    'help' => t('This effect will enhance edges within the image with a convolution filter.'),
    'dimensions passthrough' => TRUE,
    'form callback' => 'graphicsmagick_effects_edge_form',
    'effect callback' => 'graphicsmagick_effects_edge',
    'summary theme' => 'graphicsmagick_effects_oil_paint_summary',
  );

  $effects['graphicsmagick_effects_emboss'] = array(
    'label' => t('Emboss'),
    'help' => t('This effect will convolve the image with a Gaussian operator, giving to the image a three-dimensional effect.'),
    'dimensions passthrough' => TRUE,
    'form callback' => 'graphicsmagick_effects_emboss_form',
    'effect callback' => 'graphicsmagick_effects_emboss',
    'summary theme' => 'graphicsmagick_effects_emboss_summary',
  );

  $effects['graphicsmagick_effects_enhance'] = array(
    'label' => t('Enhance'),
    'help' => t('This effect will improve the quality of a noisy image.'),
    'dimensions passthrough' => TRUE,
    'effect callback' => 'graphicsmagick_effects_enhance',
  );

  $effects['graphicsmagick_effects_equalize'] = array(
    'label' => t('Equalize'),
    'help' => t('This effect will enhance the image contrast.'),
    'dimensions passthrough' => TRUE,
    'effect callback' => 'graphicsmagick_effects_enhance',
  );

  $effects['graphicsmagick_effects_flip'] = array(
    'label' => t('Vertical mirror'),
    'help' => t('This effect will create a vertical mirror image by reflecting the pixels around the central x-axis.'),
    'dimensions passthrough' => TRUE,
    'effect callback' => 'graphicsmagick_effects_flip',
  );

  $effects['graphicsmagick_effects_flop'] = array(
    'help' => t('This effect will create a horizontal mirror image by reflecting the pixels around the central y-axis.'),
    'dimensions passthrough' => TRUE,
    'effect callback' => 'graphicsmagick_effects_flop',
  );

  $effects['graphicsmagick_effects_gamma'] = array(
    'label' => t('Gamma'),
    'help' => t("This effect will change the gamma values. The same image viewed on different devices will have perceptual differences on intensity."),
    'dimensions passthrough' => TRUE,
    'form callback' => 'graphicsmagick_effects_gamma_form',
    'effect callback' => 'graphicsmagick_effects_gamma',
    'summary theme' => 'graphicsmagick_effects_gamma_summary',
  );

  $effects['graphicsmagick_effects_noise'] = array(
    'label' => t('Add noise'),
    'help' => t("This effect will add random noise to the image."),
    'dimensions passthrough' => TRUE,
    'form callback' => 'graphicsmagick_effects_noise_form',
    'effect callback' => 'graphicsmagick_effects_noise',
    'summary theme' => 'graphicsmagick_effects_noise_summary',
  );

  $effects['graphicsmagick_effects_oil_paint'] = array(
    'label' => t('Oil paint'),
    'help' => t('This effect will simulate an oil painting. Each pixel is replaced by the most frequent color occurring in a circular region defined by radius.'),
    'dimensions passthrough' => TRUE,
    'form callback' => 'graphicsmagick_effects_oil_paint_form',
    'effect callback' => 'graphicsmagick_effects_oil_paint',
    'summary theme' => 'graphicsmagick_effects_oil_paint_summary',
  );

  $effects['graphicsmagick_effects_solarize'] = array(
    'label' => t('Solarize'),
    'help' => t('Solarize will apply a special effect to the image, similar to the effect achieved in a photo darkroom by selectively exposing areas of photo sensitive paper to light.'),
    'dimensions passthrough' => TRUE,
    'form callback' => 'graphicsmagick_effects_solarize_form',
    'effect callback' => 'graphicsmagick_effects_solarize',
    'summary theme' => 'graphicsmagick_effects_solarize_summary',
  );

  $effects['graphicsmagick_effects_spread'] = array(
    'label' => t('Spread'),
    'help' => t('This effect will randomly displace each pixel in a block defined by the radius parameter.'),
    'form callback' => 'graphicsmagick_effects_spread_form',
    'effect callback' => 'graphicsmagick_effects_spread',
    'summary theme' => 'graphicsmagick_effects_spread_summary',
  );

  $effects['graphicsmagick_effects_swirl'] = array(
    'label' => t('Swirl'),
    'help' => t('This effect will swirl the pixels about the center of the image, where degrees indicates the sweep of the arc through which each pixel is moved.'),
    'form callback' => 'graphicsmagick_effects_swirl_form',
    'effect callback' => 'graphicsmagick_effects_swirl',
    'summary theme' => 'graphicsmagick_effects_swirl_summary',
  );

  return $effects;
}

 /**
 * Implements hook_image_toolkits().
 */
function graphicsmagick_image_toolkits() {
  return array(
    'graphicsmagick_toolkit' => array(
      'title' => t('GraphicsMagick toolkit'),
      'available' => graphicsmagick_available(),
    ),
  );
}

/**
 * Implements hook_system_info_alter().
 */
function graphicsmagick_system_info_alter(&$info, $file, $type) {
  if ($type == 'module' && $file->name == 'graphicsmagick_effects' && !module_exists('graphicsmagick_effects')) {
    $info['disabled'] = TRUE;
  }
}

/**
 * Implements hook_theme().
 */
function graphicsmagick_theme() {
  $summary_base = array(
    'variables' => array( 'data' => NULL),
    'file' => 'includes/graphicsmagick.theme.inc',
  );

  return array(
    'graphicsmagick_effects_blur_summary' => $summary_base,
    'graphicsmagick_effects_edge_summary' => $summary_base,
    'graphicsmagick_effects_emboss_summary' => $summary_base,
    'graphicsmagick_effects_gamma_summary' => $summary_base,
    'graphicsmagick_effects_noise_summary' => $summary_base,
    'graphicsmagick_effects_oil_paint_summary' => $summary_base,
    'graphicsmagick_effects_solarize_summary' => $summary_base,
    'graphicsmagick_effects_spread_summary' => $summary_base,
    'graphicsmagick_effects_swirl_summary' => $summary_base,
  );
}

/**
 * Retrieves settings for the GraphicsMagick toolkit.
 */
function image_graphicsmagick_toolkit_settings() {
  $form['graphicsmagick_toolkit_image_blur'] = array(
    '#type' => 'number',
    '#title' => t('Image blur'),
    '#description' => t('The image blur (from 0.0 to 2.0). Values higher than 1.0 make the image blurry, while values lower than 1.0 make the image sharper.'),
    '#default_value' => graphicsmagick_toolkit_get_image_blur(),
    '#min' => 0.0,
    '#max' => 2.0,
    '#step' => 0.2,
  );

  $form['graphicsmagick_toolkit_image_filter'] = array(
    '#type' => 'select',
    '#title' => t('Image filter'),
    '#description' => t('The image filter applied to the image. By default no filter is applied when an image is resized. For a better effect, choose Lanczos or Mitchell.'),
    '#options' => graphicsmagick_image_filter_options(),
    '#default_value' => graphicsmagick_toolkit_get_image_filter(),
  );

  $form['graphicsmagick_toolkit_jpeg_quality'] = array(
    '#type' => 'number',
    '#title' => t('JPEG quality'),
    '#description' => t('The image quality for JPEG images (from 0 to 100). Higher values mean better image quality but bigger files.'),
    '#default_value' => graphicsmagick_toolkit_get_jpeg_quality(),
    '#min' => 0,
    '#max' => 100,
    '#step' => 1,
  );

  $form['graphicsmagick_toolkit_png_compression'] = array(
    '#type' => 'number',
    '#title' => t('PNG compression'),
    '#description' => t('The PNG compression (from 0 to 99). Higher values do not mean better compression, although 99 usually compresses a PNG image more than other values. Verify the file size once the image has been saved.'),
    '#default_value' => graphicsmagick_toolkit_get_png_compression(),
    '#min' => 0,
    '#max' => 100,
    '#step' => 1,
  );

  return $form;
}

/**
 * Retrieves the supported extensions for the GraphicsMagick toolkit.
 */
function image_graphicsmagick_toolkit_supported_extensions() {
  // The following list doesn't include all the file types recognized by the
  // GraphicsMagick library; it includes most of the image types, excluding
  // the raw images and those images the Gmagick class is not able to write.
  $extensions = array(
    'BMP' => 'bmp',
    'CIN' => 'cin',
    'DCX' => 'dcx',
    'DPX' => 'dpx',
    'EPI' => 'epi',
    'EPSF' => 'eps',
    'EPSI' => 'eps',
    'EPT' => 'eps',
    'EPT2' => 'eps',
    'EPT3' => 'eps',
    'EPS' => 'eps',
    'FITS' => 'fits',
    'GIF87' => 'gif',
    'GIF' => 'gif',
    'ICB' => 'icb',
    'JPEG' => 'jpeg',
    'JPG' => 'jpg',
    'PAM' => 'pam',
    'PBM' => 'pbm',
    'EPDF' => 'pdf',
    'PDF' => 'pdf',
    'PGM' => 'pgm',
    'PNG00' => 'png',
    'PNG24' => 'png',
    'PNG32' => 'png',
    'PNG48' => 'png',
    'PNG' => 'png',
    'PNM' => 'pnm',
    'PPM' => 'ppm',
    'PS' => 'ps',
    'SGI' => 'sgi',
    'TGA' => 'tga',
    'PTIF' => 'tif',
    'BIGTIFF' => 'tif',
    'TIFF' => 'tiff',
    'VDA' => 'vda',
    'VST' => 'vst',
    'WBMP' => 'wbmp',
    'WEBP' => 'webp',
    'XBM' => 'xbm',
    'PICON' => 'xpm',
  );
  $supported_extensions = array();

  try {
    $handler = new Gmagick();

    foreach ($handler->queryFormats() as $format) {
      if (isset($extensions[$format])) {
        $supported_extensions[] = $extensions[$format];
      }
    }
  }
  catch (GmagickException) {
    // Ignore the thrown exception.
  }

  // The returned extensions exclude raw images.
  return array_unique($supported_extensions);
}

/**
 * Scales an image to the specified size using the GraphicsMagick library.
 *
 * @param object $image
 *   An image object. The $image->info['width'] and $image->info['height']
 *   values will be modified by this call.
 * @param int $width
 *   The new width of the resized image, in pixels.
 * @param int $height
 *   The new height of the resized image, in pixels.
 * @param int|string $background
 *   A hexadecimal integer specifying the background color to use for the
 *   uncovered area of the image after the rotation, for example 0x000000 for
 *   black or 0xff00ff for magenta. The default value is 0xFFFFFF.
 *
 * @return bool
 *   TRUE or FALSE, based on success.
 *
 * @see image_resize()
 */
function image_graphicsmagick_toolkit_resize($image, $width, $height, $background = NULL) {
  $blur = graphicsmagick_toolkit_get_image_blur();
  $filter = graphicsmagick_toolkit_get_image_filter();

  try {
    $color = Color::toHex($background);
  }
  catch (\InvalidArgumentException $e) {
    watchdog_exception('graphicsmagick', $e);
    return FALSE;
  }

  $effect = (new class {
    public function __invoke($handler, $data) {
      return $handler->resizeImage($data['width'], $data['height'], $data['filter'], $data['blur']);
    }
  });

  try {
    $background = Color::toHex($color);
  }
  catch (\InvalidArgumentException $e) {
    watchdog_exception('graphicsmagick', $e);
    return FALSE;
  }

  $data = array(
    'width' => $width,
    'height' => $height,
    'background' => $background,
    'blur' => $blur,
    'filter' => $filter,
  );
  $result = graphicsmagick_image_effect($image, $effect, $data);

  try {
    // The following methods could throw an exception. In the case they do, use
    // the width and height values passed to the method.
    $new_width = $image->handler->getImageWidth();
    $new_height = $image->handler->getImageHeight();
  }
  catch (GmagickException) {
    $new_width = $width;
    $new_height = $height;
  }

  $image->info['width'] = $new_width;
  $image->info['height'] = $new_height;

  return $result;
}

/**
 * Rotates an image the given number of degrees.
 *
 * @param object $image
 *   An image object. The $image->info['width'] and $image->info['height']
 *   values will be modified by this call.
 * @param int $degrees
 *   The number of (clockwise) degrees to rotate the image.
 * @param int|string $background
 *   A hexadecimal value specifying the background color to use for the
 *   uncovered area of the image after the rotation, for example 0x000000 for
 *   black or 0xff00ff for magenta. The default value is #FFFFFF.
 *
 * @return bool
 *   TRUE or FALSE, based on success.
 *
 * @see image_rotate()
 */
function image_graphicsmagick_toolkit_rotate($image, $degrees, $background = NULL) {
  try {
    $color = Color::toHex($background);
  }
  catch (\InvalidArgumentException $e) {
    watchdog_exception('graphicsmagick', $e);
    return FALSE;
  }

  $data = array(
    'color' => $color,
    'degrees' => $degrees,
  );
  $effect = (new class {
    public function __invoke($handler, $data) {
      return $handler->rotateImage($data['color'], $data['degrees']);
    }
  });

  return graphicsmagick_image_effect($image, $effect, $data);
}

/**
 * Crops an image using the GraphicsMagick library.
 *
 * @param object $image
 *   An image object. The $image->info['width'] and $image->info['height']
 *   values will be modified by this call.
 * @param int $x
 *   The starting x offset at which to start the crop, in pixels.
 * @param int $y
 *   The starting y offset at which to start the crop, in pixels.
 * @param int $width
 *   The width of the cropped area, in pixels.
 * @param int $height
 *   The height of the cropped area, in pixels.
 * @param int|string $background
 *   A hexadecimal value specifying the background color to use for the
 *   uncovered area of the image after the rotation, for example 0x000000 for
 *   black or 0xff00ff for magenta. The default value is #FFFFFF.
 *
 * @return bool
 *   TRUE or FALSE, based on success.
 *
 * @see image_crop()
 */
function image_graphicsmagick_toolkit_crop($image, $x, $y, $width, $height, $background = NULL) {
  try {
    $color = Color::toHex($background);
  }
  catch (\InvalidArgumentException $e) {
    watchdog_exception('graphicsmagick', $e);
    return FALSE;
  }

  $data = array(
    'background' => $color,
    'width' => $width,
    'height' => $height,
    'x' => $x,
    'y' => $y,
  );
  $effect = (new class {
    public function __invoke($handler, $data) {
      $handler = $handler->cropImage($data['width'], $data['height'], $data['x'], $data['y']);

      // This method is not documented on
      // https://www.php.net/manual/en/class.gmagick.php.
      // Verify it is implemented before using it.
      if (method_exists($handler, 'setImagePage')) {
        $handler = $handler->setImagePage($data['width'], $data['height'], $data['x'], $data['y']);
      }

      return $handler;
    }
  });

  $result = graphicsmagick_image_effect($image, $effect, $data);

  try {
    // The following methods could throw an exception. In the case they do, use
    // the width and height values passed to the method.
    $new_width = $image->handler->getImageWidth();
    $new_height = $image->handler->getImageHeight();
  }

  catch (GmagickException) {
    $new_width = $width;
    $new_height = $height;
  }

  $image->info['width'] = $new_width;
  $image->info['height'] = $new_height;

  return TRUE;
}

/**
 * Converts an image to grayscale.
 *
 * @param object $image
 *   An image object.
 *
 * @return bool
 *   TRUE or FALSE, based on success.
 *
 * @see image_desaturate()
 */
function image_graphicsmagick_toolkit_desaturate($image) {
  $effect = (new class {
    public function __invoke($handler, $data) {
      return $handler->setImageType(Gmagick::IMGTYPE_GRAYSCALE);
    }
  });

  return graphicsmagick_image_effect($image, $effect, array());
}

/**
 * Loads an image from a file.
 *
 * @param object $image
 *   An image object. The $image->handler and $image->format values will be
 *   populated by this call.
 *
 * @return bool
 *   TRUE or FALSE, based on success.
 *
 * @see image_load()
 * @see graphicsmagick_image_load()
 */
function image_graphicsmagick_toolkit_load($image) {
  return graphicsmagick_image_load($image);
}

/**
 * Writes an image to a destination file.
 *
 * @param object $image
 *   An image object. The $image->handler value will be changed by this call.
 * @param string $destination
 *   A URI or file path where the image should be saved.
 *
 * @return bool
 *   TRUE or FALSE, based on success.
 *
 * @see image_save()
 * @see graphicsmagick_image_save()
 */
function image_graphicsmagick_toolkit_save($image, $destination) {
  return graphicsmagick_image_save($image, $destination);
}

/**
 * Gets details about an image.
 *
 * @param object $image
 *   An image object.
 *
 * @return false|array
 *   FALSE, if the file could not be found or is not an image. Otherwise, a
 *   keyed array containing information about the image:
 *   - "width": Width, in pixels.
 *   - "height": Height, in pixels.
 *   - "extension": Commonly used file extension for the image.
 *   - "mime_type": MIME type (for example 'image/jpeg' or 'image/gif').
 *
 * @see image_get_info()
 */
function image_graphicsmagick_toolkit_get_info($image) {
  $details = array(
    'width' => 0,
    'height' => 0,
  );

  try {
    $handler = new Gmagick(backdrop_realpath($image->source));
    $details['width'] = $handler->getImageWidth();
    $details['height'] = $handler->getImageHeight();
  }
  catch (GmagickException) {
    // An exception has been thrown when trying to access the image information,
    // which could also mean the image file is corrupted. Return FALSE to signal
    // an error.
      return FALSE;
  }

  return $details;
}

/**
 * Form structure for the blur effect.
 *
 * Note that this is not a complete form; it only contains the portion of the
 * form for configuring the effect options. Therefore, it does not need to
 * include metadata about the effect, nor a submit button.
 *
 * @param array $data
 *   The current configuration for this effect.
 */
function graphicsmagick_effects_blur_form(array $data) {
  $form['radius'] = array(
    '#type' => 'number',
    '#title' => t('Radius'),
    '#description' => t('This value should typically be either 0, to let the effect choose the best value, or be twice the sigma value.'),
    '#default_value' => $data['radius'] ?? 0.0,
    '#required' => TRUE,
    '#min' => 0.0,
    '#max' => 65355.0,
    '#step' => 0.5,
  );
  $form['sigma'] = array(
    '#type' => 'number',
    '#title' => t('Sigma'),
    '#description' => t('A large sigma value and a smallish radius value will introduce artifacts in the resulting image; small sigma values are typically only used to fuzz lines and smooth edges on images for which no anti-aliasing was used.'),
    '#default_value' => $data['sigma'] ?? 1.0,
    '#required' => TRUE,
    '#min' => 0.0,
    '#max' => 65355.0,
    '#step' => 0.5,
  );

  return $form;
}

/**
 * Image effect callback; blur an image.
 *
 * @param object $image
 *   An image object.
 * @param array $data
 *   An array of attributes to use when performing the bluring effect with the
 *   following items:
 *   - "radius": A float representing the Gaussian radius.
 *   - "sigma": A float representing the Gaussian sigma.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function graphicsmagick_effects_blur($image, array $data) {
  $effect = (new class {
    public function __invoke($handler, $data) {
      return $handler->blurImage($data['radius'], $data['sigma']);
    }
  });

  return graphicsmagick_image_effect($image, $effect, $data);
}

/**
 * Image effect callback; reduce the speckle noise in an image.
 *
 * @param object $image
 *   An image object.
 * @param array $data
 *   An array of attributes to use when despeckling the image. No attributes are
 *   currently used for this effect.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function graphicsmagick_effects_despeckle($image, array $data) {
  $effect = (new class {
    public function __invoke($handler, $data) {
      return $handler->despeckleImage();
    }
  });

  return graphicsmagick_image_effect($image, $effect, $data);
}

/**
 * Form structure for the edge effect.
 *
 * Note that this is not a complete form; it only contains the portion of the
 * form for configuring the effect options. Therefore, it does not need to
 * include metadata about the effect, nor a submit button.
 *
 * @param array $data
 *   The current configuration for this effect.
 */
function graphicsmagick_effects_edge_form(array $data) {
  $form['radius'] = array(
    '#type' => 'number',
    '#title' => t('Radius'),
    '#description' => t('Use a value of zero to let the effect choose the best value.'),
    '#default_value' => $data['radius'] ?? 0.0,
    '#required' => TRUE,
    '#min' => 0.0,
    '#max' => 65355.0,
    '#step' => 0.5,
  );

  return $form;
}

/**
 * Image effect callback; enhance the image edges.
 *
 * @param object $image
 *   An image object.
 * @param array $data
 *   An array of attributes to use when enhancing the image edges with the
 *   following items:
 *   - "radius": The operation radius.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function graphicsmagick_effects_edge($image, array $data) {
  $effect = (new class {
    public function __invoke($handler, $data) {
      return $handler->edgeImage($data['radius']);
    }
  });

  return graphicsmagick_image_effect($image, $effect, $data);
}

/**
 * Form structure for the emboss effect.
 *
 * Note that this is not a complete form; it only contains the portion of the
 * form for configuring the effect options. Therefore, it does not need to
 * include metadata about the effect, nor a submit button.
 *
 * @param array $data
 *   The current configuration for this effect.
 */
function graphicsmagick_effects_emboss_form(array $data) {
  $form['radius'] = array(
    '#type' => 'number',
    '#title' => t('Radius'),
    '#description' => t('For reasonable results, the radius value should be higher than the sigma value. Use a value of zero to let the effect choose the best value.'),
    '#default_value' => $data['radius'] ?? 0.0,
    '#required' => TRUE,
    '#min' => 0.0,
    '#max' => 65355.0,
    '#step' => 0.5,
  );
  $form['sigma'] = array(
    '#type' => 'number',
    '#title' => t('Sigma'),
    '#description' => t('A large sigma value works well also with color image. It can remove color dominance, but it could also introduce artifacts, especially in JPEG images.'),
    '#default_value' => $data['sigma'] ?? 1.0,
    '#required' => TRUE,
    '#min' => 0.0,
    '#max' => 65355.0,
    '#step' => 0.5,
  );

  return $form;
}

/**
 * Image effect callback; emboss an image.
 *
 * @param object $image
 *   An image object.
 * @param array $data
 *   An array of attributes to use when performing the emboss effect with the
 *   following items:
 *   - "radius": A float representing the Gaussian radius.
 *   - "sigma": A float representing the Gaussian sigma.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function graphicsmagick_effects_emboss($image, array $data) {
  $effect = (new class {
    public function __invoke($handler, $data) {
      return $handler->embossImage($data['radius'], $data['sigma']);
    }
  });

  return graphicsmagick_image_effect($image, $effect, $data);
}

/**
 * Image effect callback; enhance an image.
 *
 * @param object $image
 *   An image object.
 * @param array $data
 *   An array of attributes to use when enhancing an image. No attributes are
 *   currently used for this effect.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to blur the image.
 */
function graphicsmagick_effects_enhance($image, array $data) {
  $effect = (new class {
    public function __invoke($handler, $data) {
      return $handler->enhanceImage();
    }
  });

  return graphicsmagick_image_effect($image, $effect, $data);
}

/**
 * Image effect callback; equalize an image.
 *
 * @param object $image
 *   An image object.
 * @param array $data
 *   An array of attributes to use when equalizing an image. No attributes are
 *   currently used for this effect.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function graphicsmagick_effects_equalize($image, array $data) {
  $effect = (new class {
    public function __invoke($handler, $data) {
      return $handler->equalizeImage();
    }
  });

  return graphicsmagick_image_effect($image, $effect, $data);
}

/**
 * Image effect callback; create a vertical mirror image.
 *
 * @param object $image
 *   An image object.
 * @param array $data
 *   An array of attributes to use when creating a vertical mirror image. No
 *   attributes are currently used for this effect.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function graphicsmagick_effects_flip($image, array $data) {
  $effect = (new class {
    public function __invoke($handler, $data) {
      return $handler->flipImage();
    }
  });

  return graphicsmagick_image_effect($image, $effect, $data);
}

/**
 * Image effect callback; create a horizontal mirror image.
 *
 * @param object $image
 *   An image object.
 * @param array $data
 *   An array of attributes to use when creating a horizontal mirror image. No
 *   attributes are currently used for this effect.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function graphicsmagick_effects_flop($image, array $data) {
  $effect = (new class {
    public function __invoke($handler, $data) {
      return $handler->flopImage();
    }
  });

  return graphicsmagick_image_effect($image, $effect, $data);
}

/**
 * Form structure for the gamma effect.
 *
 * Note that this is not a complete form; it only contains the portion of the
 * form for configuring the effect options. Therefore, it does not need to
 * include metadata about the effect, nor a submit button.
 *
 * @param array $data
 *   The current configuration for this effect.
 */
function graphicsmagick_effects_gamma_form(array $data) {
  $form['gamma'] = array(
    '#type' => 'number',
    '#title' => t('Gamma'),
    '#description' => t('Values typically range from 0.8 to 2.3. Values lower than one make the image darker; values higher than one make the image lighter.'),
    '#default_value' => $data['gamma'] ?? 0.8,
    '#required' => TRUE,
    '#min' => 0.0,
    '#max' => 10.0,
    '#step' => 0.2,
  );

  return $form;
}

/**
 * Image effect callback; change the image gamma value.
 *
 * @param object $image
 *   An image object.
 * @param array $data
 *   An array of attributes to use when changing the gamma value with the
 *   following items:
 *   - "gamma": A float representing the new gamma value.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function graphicsmagick_effects_gamma($image, array $data) {
  $effect = (new class {
    public function __invoke($handler, $data) {
      return $handler->gammaImage($data['gamma']);
    }
  });

  return graphicsmagick_image_effect($image, $effect, $data);
}

/**
 * Form structure for the noise effect.
 *
 * Note that this is not a complete form; it only contains the portion of the
 * form for configuring the effect options. Therefore, it does not need to
 * include metadata about the effect, nor a submit button.
 *
 * @param array $data
 *   The current configuration for this effect.
 */
function graphicsmagick_effects_noise_form(array $data) {
  $form['noise'] = array(
    '#type' => 'select',
    '#title' => t('Noise type'),
    '#description' => t('The noise type changes for which pixels the color is randomly changed.'),
    '#options' => graphicsmagick_image_noise_options(),
    '#default_value' => $data['noise'] ?? Gmagick::NOISE_UNIFORM,
    '#required' => TRUE,
  );

  return $form;
}

/**
 * Image effect callback; add random noise.
 *
 * @param object $image
 *   An image object.
 * @param array $data
 *   An array of attributes to use when applying the effect with the
 *   following items:
 *   - "noise": The noise type.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function graphicsmagick_effects_noise($image, array $data) {
  $effect = (new class {
    public function __invoke($handler, $data) {
      return $handler->addNoiseImage($data['radius']);
    }
  });

  return graphicsmagick_image_effect($image, $effect, $data);
}

/**
 * Form structure for the oil painting effect.
 *
 * Note that this is not a complete form; it only contains the portion of the
 * form for configuring the effect options. Therefore, it does not need to
 * include metadata about the effect, nor a submit button.
 *
 * @param array $data
 *   The current configuration for this effect.
 */
function graphicsmagick_effects_oil_paint_form(array $data) {
  $form['radius'] = array(
    '#type' => 'number',
    '#title' => t('Radius'),
    '#description' => t('Each pixel is replaced by the most frequent color occurring in a circular region defined by the radius value.'),
    '#default_value' => $data['radius'] ?? 0.8,
    '#required' => TRUE,
    '#min' => 0.6,
    '#max' => 50.0,
    '#step' => 0.2,
  );

  return $form;
}

/**
 * Image effect callback; simulate an oil painting.
 *
 * @param object $image
 *   An image object.
 * @param array $data
 *   An array of attributes to use when applying the effect with the
 *   following items:
 *   - "radius": A float representing the radius of the circular region used
 *     to calculate the most frequent color.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function graphicsmagick_effects_oil_paint($image, array $data) {
  $effect = (new class {
    public function __invoke($handler, $data) {
      return $handler->oilPaintImage($data['radius']);
    }
  });

  return graphicsmagick_image_effect($image, $effect, $data);
}

/**
 * Form structure for the solarize effect.
 *
 * Note that this is not a complete form; it only contains the portion of the
 * form for configuring the effect options. Therefore, it does not need to
 * include metadata about the effect, nor a submit button.
 *
 * @param array $data
 *   The current configuration for this effect.
 */
function graphicsmagick_effects_solarize_form(array $data) {
  try {
    $gmagick = new Gmagick();
    $quantum_level = $gmagick->getQuantumDepth()['quantumDepthLong'];
  }
  catch (Exception) {
    // As getting the quantum dept value failed, assume its value is 8.
    $quantum_level = 8;
  }

  $level = $data['level'] ?? 1 << (($quantum_level / 2) - 2);

  $form['level'] = array(
    '#type' => 'number',
    '#title' => t('Level'),
    '#description' => t('The effect level.'),
    '#default_value' => $level,
    '#required' => TRUE,
    '#min' => 0,
    '#max' => 1 << $quantum_level,
    '#step' => 1,
  );

  return $form;
}

/**
 * Image effect callback; simulate a solarize effect.
 *
 * @param object $image
 *   An image object.
 * @param array $data
 *   An array of attributes to use when applying the effect with the
 *   following items:
 *   - "level": An integer representing the level of the effect.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function graphicsmagick_effects_solarize($image, array $data) {
  $effect = (new class {
    public function __invoke($handler, $data) {
      return $handler->solarizeImage($data['level']);
    }
  });

  return graphicsmagick_image_effect($image, $effect, $data);
}

/**
 * Form structure for the spread effect.
 *
 * Note that this is not a complete form; it only contains the portion of the
 * form for configuring the effect options. Therefore, it does not need to
 * include metadata about the effect, nor a submit button.
 *
 * @param array $data
 *   The current configuration for this effect.
 */
function graphicsmagick_effects_spread_form(array $data) {
  $form['radius'] = array(
    '#type' => 'number',
    '#title' => t('Radius'),
    '#description' => t('Each pixel in a block defined by the radius parameter is randomly displaced.'),
    '#default_value' => $data['radius'] ?? 2.0,
    '#required' => TRUE,
    '#min' => 0.0,
    '#max' => 50.0,
    '#step' => 0.4,
  );

  return $form;
}

/**
 * Image effect callback; randomly displace each pixel in a circular region.
 *
 * @param object $image
 *   An image object.
 * @param array $data
 *   An array of attributes to use when applying the effect with the
 *   following items:
 *   - "radius":  A float representing the radius of the circular region
 *     where the pixels are randomly displaced.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function graphicsmagick_effects_spread($image, array $data) {
  $effect = (new class {
    public function __invoke($handler, $data) {
      return $handler->spreadImage($data['radius']);
    }
  });

  return graphicsmagick_image_effect($image, $effect, $data);
}

/**
 * Form structure for the swirl effect.
 *
 * Note that this is not a complete form; it only contains the portion of the
 * form for configuring the effect options. Therefore, it does not need to
 * include metadata about the effect, nor a submit button.
 *
 * @param array $data
 *   The current configuration for this effect.
 */
function graphicsmagick_effects_swirl_form(array $data) {
  $form['degrees'] = array(
    '#type' => 'number',
    '#title' => t('Degrees'),
    '#description' => t('The sweep of the arc through which each pixel is moved.'),
    '#default_value' => $data['degrees'] ?? 10.0,
    '#required' => TRUE,
    '#min' => 0.0,
    '#max' => 360.0,
    '#step' => 2.0,
  );

  return $form;
}

/**
 * Image effect callback; randomly displace each pixel in a circular region.
 *
 * @param object $image
 *   An image object.
 * @param array $data
 *   An array of attributes to use when applying the effect with the
 *   following items:
 *   - "degrees":  A float representing the sweep of the arc through which each
 *     pixel is moved.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function graphicsmagick_effects_swirl($image, array $data) {
  $effect = (new class {
    public function __invoke($handler, $data) {
      return $handler->swirlImage($data['degrees']);
    }
  });

  return graphicsmagick_image_effect($image, $effect, $data);
}

/**
 * Returns the image quality to use with JPEG images.
 *
 * @return int
 *   The image quality for JPEG images, a value between 0 and 100, where 95 is
 *   the default value.
 */
function graphicsmagick_toolkit_get_jpeg_quality() {
  $value = config_get('graphicsmagick_toolkit_jpeg_quality');

  // If the JPEG quality value hasn't been set, return 80 instead of 0, which
  // would be a bad image quality to use by default.
  return $value ?? 80;
}

/**
 * Returns the compression value to use with PNG images.
 *
 * @return int
 *   The compression value for PNG images, a value between 0 and 99, where 99 is
 *   the default value.
 */
function graphicsmagick_toolkit_get_png_compression() {
  $value = config_get('graphicsmagick_toolkit_png_compression');

  // If the PNG compression value hasn't been set, return 99 instead of 0, which
  // is a better compression value to use by default.
  return $value ?? 99;
}

/**
 * Returns the blur value required by some image manipulation methods.
 *
 * @return float
 *   A value between 0.0 and 2.0 where 1.0 is
 *   the default value.
 */
function graphicsmagick_toolkit_get_image_blur() {
  $value = config_get('graphicsmagick_toolkit_image_blur');

  // If the blur value hasn't been set, return 1.0 instead of 0.
  return $value ?? 1.0;
}

/**
 * Returns the filter to use in some image manipulation methods.
 *
 * @return int
 *   The filter value set in the settings form. It uses the
 *   Gmagick::FILTER_* constants.
 */
function graphicsmagick_toolkit_get_image_filter() {
  $value = config_get('graphicsmagick_toolkit_image_filter');

  // If  the filter value hasn't been set, return Gmagick::FILTER_LANCZOS.
  return $value ?? Gmagick::FILTER_LANCZOS;
}

/**
 * Verifies the methods used from the GraphicsMagick toolkit can be used.
 *
 * This function could be used from the modules that need to use the Gmagick
 * extension to alter images, as the methods this function checks are necessary
 * to handle animated images.
 *
 * @return bool
 *   TRUE when the Gmagick PHP extension is loaded, the Gmagick class it
 *   implements is available, and that class implements the methods used by the
 *   toolkit.
 */
function graphicsmagick_available() {
  if (extension_loaded('gmagick') && class_exists('Gmagick')) {
    try {
      $handler = new Gmagick();

      // Verify the undocumented methods used by the toolkit are implemented.
      $missing_methods = FALSE;
      $missing_methods |= !method_exists($handler, 'getNumberImages');
      $missing_methods |= !method_exists($handler, 'coalesceImages');
      $missing_methods |= !method_exists($handler, 'deconstructImages');

      return !$missing_methods;
    }
    catch (GmagickException) {
      return FALSE;
    }
  }

  return FALSE;
}

/**
 * Loads an image from a file.
 *
 * This function can be used from any module that needs to use the effects
 * implemented by the GraphicsMagick Effects modules independently of the
 * toolkit set for the site. In the case the used toolkit is not
 * GraphicsMagick Toolkit, this function could cause the image to be loaded
 * again, with the consequence that the image data is loaded twice in memory.
 *
 * $image->source is expected to contain the source file path. If it has not
 * been set, or it does not contain the expected value, this function will
 * return FALSE.
 *
 * @param object $image
 *   An image object. The $image->handler, and $image->format, and
 *   $image->mimeType values will be populated by this call.
 *
 * @return bool
 *   TRUE or FALSE, based on success.
 */
function graphicsmagick_image_load($image) {
  if (isset($image->handler) && !is_a($image->handler, 'Gmagick')) {
    // $image->handler has been already set, but it is not a Gmagick instance.
    // To avoid conflicts with other modules, avoid to load the image and return
    // FALSE.
    return FALSE;
  }

  if (isset($image->handler)) {
    // Destroy the existing Gmagick instance.
    try {
      $image->handler->destroy();
    } catch (GmagickException) {
      // Ignore the exception, as there is not anything that can be done when
      // destroying a Gmagick instance fails.
    }

    $image->handler = NULL;
  }

  try {
    if (!isset($image->source) || !is_string($image->source)) {
      // $image->source must be set to a string containing the source file path.
      // Return FALSE for error in case it is not.
      return FALSE;
    }

    $handler = new Gmagick(backdrop_realpath($image->source));
    $format = $handler->getImageFormat();
  } catch (GmagickException) {
    // If either the constructor or getImageFormat() returned an
    // exception, report a failure to the calling function. An exception in
    // those cases could mean the file doesn't contain an image, it does not
    // contain an image recognized from the Gmagick class, or the file is
    // corrupted.
    return FALSE;
  }

  $image->handler = $handler;
  $image->format = $format;
  $image->mimeType = graphicsmagick_image_format_to_mime_type($format);

  return TRUE;
}

/**
 * Retrieves the image format as defined by the Gmagick class.
 *
 * @param object $image
 *   The image object.
 *
 * @return false|string
 *   FALSE in case of error, or a string containing one of the format recognized
 *   by the Gmagick class.
 */
function graphicsmagick_image_format($image) {
  if (isset($image->handler) && !is_a($image->handler, 'Gmagick')) {
    // $image->handler has been already set, but it is not a Gmagick instance.
    // To avoid conflicts with other modules, avoid to load the image and return
    // FALSE.
    return FALSE;
  }

  if (!isset($image->handler)) {
    if (!graphicsmagick_image_load($image)) {
      // The file does not contain an image, it does not contain an image
      // recognized from the Gmagick class, the file is corrupted, or creating a
      // Gmagick instance was not possible for other reasons. Return FALSE.
      return FALSE;
    }
  }

  // Return the $image->format value previously set only when $image->handler is
  // a Gmagick instance.
  if (isset($image->format)) {
    return $image->format;
  }

  try {
    $format = $image->handler->getImageFormat();
  } catch (GmagickException) {
    // If Gmagick::getImageFormat() returned an exception, report a failure to
    // the calling function. An exception in this case could mean the file
    // does not contain an image, it does not contain an image recognized from
    // the Gmagick class, or the file is corrupted.
    return FALSE;
  }

  $image->format = $format;

  return $format;
}

/**
 * Returns the option array for the filters implemented by the Gmagick class.
 *
 * @return array
 *   An array whose keys are the Gmagick::FILTER_* constants and the values are
 *   the filter names to shown in forms.
 */
function graphicsmagick_image_filter_options() {
  return array(
    Gmagick::FILTER_UNDEFINED => t('None'),
    Gmagick::FILTER_POINT => t('Point'),
    Gmagick::FILTER_BOX => t('Box'),
    Gmagick::FILTER_TRIANGLE => t('Triangle'),
    Gmagick::FILTER_HERMITE => t('Hermite'),
    Gmagick::FILTER_HANNING => t('Hanning'),
    Gmagick::FILTER_HAMMING => t('Hamming'),
    Gmagick::FILTER_BLACKMAN => t('Blackman'),
    Gmagick::FILTER_GAUSSIAN => t('Gaussian'),
    Gmagick::FILTER_QUADRATIC => t('Quadratic'),
    Gmagick::FILTER_CUBIC => t('Cubic'),
    Gmagick::FILTER_CATROM => t('Catmull-Rom'),
    Gmagick::FILTER_MITCHELL => t('Mitchell'),
    Gmagick::FILTER_LANCZOS => t('Lanczos'),
    Gmagick::FILTER_BESSEL => t('Bessel'),
    Gmagick::FILTER_SINC => t('Sinc'),
  );
}

/**
 * Returns the option array for noise types implemented by the Gmagick class.
 *
 * @return array
 *   An array whose keys are the Gmagick::NOISE_* constants and the values are
 *   the noise names to shown in forms.
 */
function graphicsmagick_image_noise_options() {
  return array(
    Gmagick::NOISE_UNIFORM => t('Uniform'),
    Gmagick::NOISE_GAUSSIAN => t('Gaussian'),
    Gmagick::NOISE_MULTIPLICATIVEGAUSSIAN => t('Multiplicative Gaussian'),
    Gmagick::NOISE_LAPLACIAN => t('Laplacian'),
    Gmagick::NOISE_POISSON => t('Poisson'),
  );
}

/**
 * Converts the format returned by the Gmagick class in the image extension.
 *
 * Modules can get the image format required from this function using
 * graphicsmagick_image_format(), without accessing any method implemented by
 * the Gmagick class.
 *
 * @param string $format
 *   The image format returned from the Gmagick class.
 *
 * @return string
 *   The image extension used by default for that image format.
 *
 * @see graphicsmagick_image_format()
 */
function graphicsmagick_image_format_to_extension($format) {
  // The following list doesn't include all the file types recognized by the
  // GraphicsMagick library; it includes most of the image types, excluding
  // the raw images and those images the Gmagick class is not able to write.
  $extensions = array(
    'BMP' => 'bmp',
    'CIN' => 'cin',
    'DCX' => 'dcx',
    'DPX' => 'dpx',
    'EPI' => 'epi',
    'EPSF' => 'eps',
    'EPSI' => 'eps',
    'EPT' => 'eps',
    'EPT2' => 'eps',
    'EPT3' => 'eps',
    'EPS' => 'eps',
    'FITS' => 'fits',
    'GIF87' => 'gif',
    'GIF' => 'gif',
    'ICB' => 'icb',
    'JPEG' => 'jpeg',
    'JPG' => 'jpg',
    'PAM' => 'pam',
    'PBM' => 'pbm',
    'EPDF' => 'pdf',
    'PDF' => 'pdf',
    'PGM' => 'pgm',
    'PNG00' => 'png',
    'PNG24' => 'png',
    'PNG32' => 'png',
    'PNG48' => 'png',
    'PNG' => 'png',
    'PNM' => 'pnm',
    'PPM' => 'ppm',
    'PS' => 'ps',
    'SGI' => 'sgi',
    'TGA' => 'tga',
    'PTIF' => 'tif',
    'BIGTIFF' => 'tif',
    'TIFF' => 'tiff',
    'VDA' => 'vda',
    'VST' => 'vst',
    'WBMP' => 'wbmp',
    'WEBP' => 'webp',
    'XBM' => 'xbm',
    'PICON' => 'xpm',
  );

  try {
    $handler = new Gmagick();
    $supported_formats = $handler->queryFormats();
  }
  catch (GmagickException) {
    // Return an empty string to signal an error.
    return '';
  }

  if (in_array($format, $supported_formats) && isset($extensions[$format])) {
    return $extensions[$format];
  }
  else {
    // If a format is not in $extensions, return an empty string, since
    // Gmagick::queryFormats() returns also video formats and raw image formats.
    return '';
  }
}

/**
 * Converts the format returned by the Gmagick class in the image MIME type.
 *
 * Modules can get the image format required from this function using
 * graphicsmagick_image_format(), without accessing any method implemented by
 * the Gmagick class.
 *
 * @param string $format
 *   The image format returned from the Gmagick class.
 *
 * @return string
 *   The image MIME type.
 *
 * @see graphicsmagick_image_format()
 */
function graphicsmagick_image_format_to_mime_type($format) {
  // Since the Gmagick class doesn't provide a method to obtain an image MIME
  // type, differently from the Imagick class, this code maps the Gmagick
  // format to the MIME type using a literal array. There is no need to use
  // mime_content_type() nor finfo_open()/finfo_file(), since the Gmagick
  // class already recognized the file type.
  // The following list doesn't include all the file types recognized by the
  // GraphicsMagick library; it includes most of the image types, excluding
  // the raw images and those images the Gmagick class is not able to write.
  $mime_types = array(
    'BIGTIFF' => 'image/tiff',
    'BMP' => 'image/x-ms-bmp',
    'CIN' => 'image/cineon',
    'DCX' => 'image/x-pc-paintbrush',
    'DPX' => 'image/x-dpx',
    'EPDF' => 'application/pdf',
    'EPI' => 'application/postscript',
    'EPS' => 'application/postscript',
    'EPSF' => 'application/postscript',
    'EPSI' => 'application/postscript',
    'EPT' => 'image/eps',
    'EPT2' => 'image/eps',
    'EPT3' => 'image/eps',
    'FITS' => 'image/fits',
    'GIF' => 'image/gif',
    'GIF87' => 'image/gif',
    'ICB' => 'image/x-tga',
    'JPEG' => 'image/jpeg',
    'JPG' => 'image/jpeg',
    'PAM' => 'image/x-portable-pixmap',
    'PBM' => 'image/x-portable-pixmap',
    'PDF' => 'application/pdf',
    'PGM' => 'image/x-portable-greymap',
    'PICON' => 'image/x-xpmi',
    'PNG' => 'image/png',
    'PNG00' => 'image/png',
    'PNG24' => 'image/png',
    'PNG32' => 'image/png',
    'PNG48' => 'image/png',
    'PNM' => 'image/x-portable-pixmap',
    'PPM' => 'image/x-portable-pixmap',
    'PS' => 'application/postscript',
    'PTIF' => 'image/tiff',
    'SGI' => 'imagine/sgi',
    'TGA' => 'image/x-tga',
    'TIFF' => 'image/tiff',
    'VDA' => 'image/x-tga',
    'VST' => 'image/x-tga',
    'WBMP' => 'image/vnd.wap.wbmp',
    'WEBP' => 'image/webp',
    'XBM' => 'image/x‑xbitmap',
  );

  try {
    $handler = new Gmagick();
    $supported_formats = $handler->queryFormats();
  }
  catch (GmagickException) {
    // Return an empty string to signal an error.
    return '';
  }

  if (in_array($format, $supported_formats) && isset($mime_types[$format])) {
    return $mime_types[$format];
  }
  else {
    // If a format is not in $mime_types, return an empty string, since
    // Gmagick::queryFormats() returns also video formats and raw image formats.
    return '';
  }
}

/**
 * Applies an effect to an image.
 *
 * @param object $image
 *   An image object. $image->handler should contain a Gmagick instance used
 *   to load the image.
 *   When the image is loaded with image_load(), and the used image toolkit is
 *   graphicsmagick_toolkit, or when the image is loaded with
 *   graphicsmagick_image_load(), $image->handler is initialized with a Gmagick
 *   instance. If $image->handler hasn't been set, this function will call
 *   graphicsmagick_image_load() to first load the image.
 *
 * @param callable $effect
 *   The callable used to apply the effect.
 * @param array $data
 *   The configuration values for the effect. All the values are passed to the
 *   effect callable, except 'background' that is used from this function to set
 *   the image background color before applying the effect.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function graphicsmagick_image_effect($image, callable $effect, array $data) {
  if (isset($image->handler) && !is_a($image->handler, 'Gmagick')) {
    // $image->handler has been already set, but it is not a Gmagick instance.
    // To avoid conflicts with other modules, avoid to save the image and return
    // FALSE.
    return FALSE;
  }

  if (!isset($image->handler)) {
    if (!graphicsmagick_image_load($image)) {
      // The file does not contain an image, it does not contain an image
      // recognized from the Gmagick class, the file is corrupted, or creating a
      // Gmagick instance was not possible for other reasons. Return FALSE.
      return FALSE;
    }
  }

  try {
    // Clone the image handler and work with the clone. In case of exceptions,
    // the original image handler and its state is preserved.
    $handler = clone $image->handler;

    if (isset($data['background'])) {
      $background = $data['background'];

      // Remove the background value to avoid to pass it to the effect callable.
      unset($data['background']);

      $original_background = $handler->getImageBackgroundColor();
      $handler->setImageBackgroundColor($background);
    }

    if ($handler->getNumberImages() > 1) {
      $handler = $handler->coalesceImages();

      do {
        $handler = $effect($handler, $data);
      } while ($handler->nextImage());

      $handler = $handler->deconstructImages();
    }
    else {
      $handler = $effect($handler, $data);
    }
  }
  catch (GmagickException $e) {
    watchdog_exception('graphicsmagick', $e);

    try {
      $handler->destroy();
    }
    catch(GmagickException) {
      // Gmagick::destroy() can throw an exception, but nothing can be done to
      // fix that.
    }

    return FALSE;
  }

  try {
    if (isset($original_background)) {
      $handler->setImageBackgroundColor($original_background);
    }

    $image->handler->destroy();
  }
  catch (GmagickException) {
    // Either Gmagick::setImageBackgroundColor() or Gmagick::destroy() can throw
    // an exception, but nothing can be done to fix that.
    // Failure to change back the background color or destroy the unused Gmagick
    // instance is not considered a failure of the image effect.
  }

  $image->handler = $handler;

  return TRUE;
}

/**
 * Writes an image to a destination file.
 *
 * @param object $image
 *   An image object. $image->handler must be a Gmagick instance; the image will
 *   be saved and the $image->handler value will be changed by this call.
 * @param string $destination
 *   A URI or file path where the image should be saved.
 *
 * @return bool
 *   TRUE or FALSE, based on success.
 *   The returned value will be FALSE even in the case the $image->handler value
 *   has been set, but it is not a Gmagick instance, or the $image->handler
 *   value has not been set, and it is not possible to load the source image.
 */
function graphicsmagick_image_save($image, $destination) {
  if (isset($image->handler) && !is_a($image->handler, 'Gmagick')) {
    // $image->handler has been already set, but it is not a Gmagick instance.
    // To avoid conflicts with other modules, avoid to save the image and return
    // FALSE.
    return FALSE;
  }

  if (!isset($image->handler)) {
    // The image has not been loaded from the file using a Gmagick instance; try
    // to load it.
    // Usually, $image->handler is already set. This code has been added to let
    // a module save an image without first calling image_load() or
    // graphicsmagick_image_load().
    if (!graphicsmagick_image_load($image)) {
      return FALSE;
    }
  }

  try {
    switch ($image->mimeType) {
      case 'image/jpeg':
        $image->handler->setCompressionQuality(graphicsmagick_toolkit_get_jpeg_quality());
        break;

      case 'image/png';
        $image->handler->setCompressionQuality(graphicsmagick_toolkit_get_png_compression());
        break;
    }

    $image->handler->writeImage(backdrop_realpath($destination), $image->handler->getNumberImages() > 1);
    return TRUE;
  } catch (GmagickException) {
    return FALSE;
  }
}
